### ISSUE TITLE
tool duplicates first row of csv data

### ISSUE THREAD

**Issue by JackDougherty** [trendct/ctnamecleaner_shiny#1]
Thanks for this tool. One small problem, which I noticed twice, is that the tool duplicates the first row of CSV data. See screenshot.

![duplicate-row](https://cloud.githubusercontent.com/assets/649719/14206780/7c88ae52-f7e3-11e5-95e0-abab9efb1a1a.png)

**Comment by andrewbtran** [comment]
Ah, Elmwood/West Hartford was in the Google Sheets twice so that threw it off. It should be fixed now.
